version: 0.2 
os: linux
phases:
  install:
    runtime-version:
      docker: 19
      nodejs: 12
  pre_build: 
    commands: 
      - //docker login with aws ecr credential
  build: 
    commands: 
      - echo Entered the build phase... 
      - echo "This is some Text" > FileName.txt
  post_build: 
    commands: 
      - echo Entered the post_build phase... 
      - echo Everything done.